# DO NOT DELETE

obj/portatom.o: port.h
obj/portmem.o: port.h
obj/strbase.o: port.h str.h
obj/strconv.o: str.h port.h
obj/except.o: except.h str.h port.h
obj/charset.o: charset.h port.h
obj/contain.o: contain.h str.h port.h
obj/baseobj.o: str.h port.h baseobj.h contain.h except.h bsearch.h
obj/source.o: source.h str.h port.h except.h charset.h contain.h baseobj.h
obj/source.o: bsearch.h
obj/langobj.o: langobj.h str.h port.h except.h baseobj.h contain.h source.h
obj/langobj.o: charset.h
obj/compiler.o: except.h str.h port.h langobj.h baseobj.h contain.h source.h
obj/compiler.o: charset.h
obj/main.o: str.h port.h except.h langobj.h baseobj.h contain.h source.h
obj/main.o: charset.h
obj/main-ut.o: charset.h port.h str.h contain.h baseobj.h except.h source.h
obj/main-ut.o: langobj.h
